name: Deploy to artifactory

on:
  # Triggers the workflow on push or pull request events but only for dev branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java SDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: OSSRH_GPG_SECRET_KEY_PASSWORD
      - name: build artifact
        run: mvn clean package
#      - name: Publish to the Maven Central Repository
#        env:
#          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
#          MAVEN_USERNAME: ${{ secrets.OSSRH_JIRA_ID }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#          OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
#        run: |
#          mvn \
#          --no-transfer-progress \
#          --batch-mode \
#          clean deploy
