name: Deploy to maven central

on:
  # Triggers the workflow on push or pull request events but only for dev branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout code
        uses: actions/checkout@v3

      - id: setup-java
        name: setup java sdk 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_JIRA_ID }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - id: install-secret-key
        name: install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG


      - id: publish-to-central
        name: publish to central repository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_JIRA_ID }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
        run: |
          mvn \
            -B \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            -s $GITHUB_WORKSPACE/settings.xml \
            clean deploy -P release
